site_name: BSA Troop 54
site_url: https://mepearson.github.io/Troop54/
site_author: Troop 54
site_description:  >-
  Content related to BSA Troop 54 for Girls, St. John the Divine, Houston, Texas

# Repository
repo_name: mepearson/troop54
repo_url: https://github.com/mepearson/troop54

# Copyright
copyright: Troop 54, Houston, TX

# Configuration
theme:
  name: material
  # custom_dir: overrides
  favicon: assets/branding/favicon.png
  logo: assets/branding/bsa-logo.svg
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.path
  #   - navigation.instant
  #   - navigation.instant.prefetch
  #   - navigation.instant.progress
  #   - navigation.top
    - toc.follow
    # - toc.integrate
  font:
    text: Open Sans
    code: Roboto

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    


# Plugins
plugins:
  - blog
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - privacy:
      links_attr_map:
        target: _blank

# Additional configuration
extra:
  social:
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/troop54houston

# Extensions  
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true  
      toc_depth: 3
  
# Page tree
nav:
  - About Troop 54: 
    - Old Home Page: about/upcoming.md
  - Youth Development:
    - Youth Leadership: leadership.md
    - Advancement: advancement.md
    - First Class Trail: fct.md
  - Outdoors Program: 
    - Weekend Campouts: camping/weekend.md
    - Summer Camp: camping/summer.md
    - Gear List: camping/gearlist.md
  - Resources:
    - Contact Us: contact.md
    - Directory / Rosters: directory.md
    - Activities - Overview: activities.md
    - Joining Troop 54: joining.md
    - Troop Handbook: Troop54-handbook.md
    - Troop Committee: committee.md
    - Training: training.md
    - Covid Policy: covid.md
    - Links to BSA sites: bsa-links.md
    - Troop Store: "https://shop.troop54houston.org/"
  - Calendar: calendar.md
  - Blog:
    - blog/index.md
  - Tags Index: tags.md
  